[package]
name = "pbweb-app"
version = "0.2.7"
edition = "2021"

[[bin]]
name = "pbweb-app"
path = "src/main.rs"

[features]
default = []
device = ["pb-sys/device"]

[dependencies]
pb-sys = { path = "../pb-sys" }
pb-core = { path = "../pb-core" }
pb-server = { path = "../pb-server" }
pb-ui = { path = "../pb-ui" }
qrcode = { version = "0.14", default-features = false }
